# only pull the last 5 commits (faster)
git:
  depth: 5

# makes sure that Travis provisions a vm and not a docker container
sudo: required

# Ubuntu 14.04 (defines the type of the linux vm)
dist: trusty

# OS X 10.11 / XCode 7.3.1 (defines the type of the osx vm)
osx_image: xcode7.3

# provides a build environment for this language
language: cpp

# spins up docker (only on linux)
services:
  - docker

# define the job matrix, i.e. tells Travis to spin up two virtual machines (osx and linux)
matrix:
  include:
  - os: linux
  - os: osx

before_install:
# decrypt archive containing the kakadu library (on osx and linux)
- openssl aes-256-cbc -K $encrypted_7deda1f68196_key -iv $encrypted_7deda1f68196_iv -in private/private.tar.enc -out private/private.tar -d
- tar xvf private/private.tar
- mv v7_9-01727L.zip vendor/.
# build the docker image (only on linux)
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t sipi . ; fi
# update and install dependencies (only on osx)
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install log4cpp; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libmagic; fi

script:
# run the build process in docker container (only on linux)
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run sipi /bin/sh -c "cd build; cmake ..; make" ; fi
# run the build process directly on the vm (only on osx)
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd build ; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake .. ; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then make ; fi

# allways send notification to our slack channel (success and failure)
# email is sent per default only on failure and once on success after failure
notifications:
  slack:
    secure: MGtrlgeHZ8F6SHmMOyOVuUac4IVSW7MF5tYGOHrRxyYuUZ5H/mADF/nHrY1wWwn9YHB460TkIma48/ctC21wyFecfvSzxfBuJtFflsXSpe8gE9DnlWaSZJgrcC7KwNcxDi4+0wIQHvFg8jbUZflsI1sB0ctMLzlt8gKQqRzjnlttznxUnU+8iEkUrPqRpFrwdL84J38Pdi4xy+7cMlx6VfaBj2UcBQz+jN22fJqOq4haCAj1w/ExrZJ1FaXJlgGafYQLV2YBeIdXrKNVV1dXpGElpOybuFbsi0XWHxHBaEALgoTZHot9QX3NXeRlm5BLVtqYXo06jFVydnnkvup44HYgPH6IFSbe4lh4kS+NKn+zbKjHwcPN2RZEvICmdpU9Gz/c0RVCPOp1NUQnnrMPcU8Q3X9LSa//y+X1nawk3vzjqeecLNZ6hJ6BAzzhF7Sy8kP5irTpGozwJtSZl8dQZX67sG7AQRpKhNw1HwGQSToasmPy8yQyVGozCoXS1m0R381xczNJcm8Ah2ApFT77VkglMwGtktWGGnYlXImwnKBK+DwJvQVkCtQ8bI5ZcGOOkH41zZ0QJ851eUMMrn2L7DDpBiZFXfp9BTWuBSIJtXTQ1SYldundmOJLKswx2rl+swngdF4cWS37lGMTiebpuxalWQ0O4uhflm7tRb0Kx9I=


