git:
  depth: 1

sudo: required

dist: trusty

language: cpp

services:
  - docker

env:
  global:
  - secure: foErFk3DvusHalHJQ4ZS0ss3Qglj2q8+4c4+o0gdaXUtmJBmwT+vdxEhH5ZQk3a/786QO35C3+JNQ4ZYo6YM3grUc9ZfEwhBmui/v8XPGAG7Wmy47xcD3v/oOgIwvc9khQdkMuVgybXDe3Ycx8UPfBvCfLm6/nbJ0vIn8gYFHUHfyglCGJBA6d8Kzh+RpYSr4k16h9IFnl7QTYc0FsPDYCiOKE+JRfwsPlFNnAfGjcnPGpowWT+NeTKw/m++FEMIFsPLmpEL5MVcPaCvgnLz7Q+y9HNMn5Pijfd7eqNR3Z1PR0QF3eWHA0LZFrZwXcTyfpEckCbArNt3NS3S3WjIxkkjWED7VfJ27cHRN/2QsOBCbCUwshqkeR3ChwwV/3ku2UgLvlVu9IDxLdNM7Z7XjHYgfXVQsdV66nNZbG/nf9kgV+qg031CEjhvZMmbnOlrWb1ybWSLOPJkJs6qz6RcNJ+HW+iy5Znm1696axEC8f2FnXSSIOrbv0XvhycYEmqIo5Hz1BpkWSuUBF0dR8Yl0dJsmZ4WVgRLktqvjcv2VqB+Yb+D+FkaZEpzWwh2w8qHOkWtYK/GqyMej8WcB1S4VYpa5XRghHQRd4IqlMimvX6Tk+tntiMrLQimuyneQwvoNk759bqqB74Ui7MTINvkU22TmTtWWFbAgHvBmLInBrA= # DOCKER_EMAIL
  - secure: WPQBoKTtyd80dNfPUvR/L83SYb3riCYtI/tyf5ReHY2lZ9y7+ZQAcb2R2YFWw7b12yAZ/HKqrA1m+6UyRtfM/HgA8BIUoMPeV0+sV9+cf7rPMNz7+iuk3wgRMDgbs5mD7w5RPWEqRuSiAjTJdDYv8gVx9SLwOVWSoM8/Uj9eccf30WkQuG024I1HUoaJBJH+7vD8qleUyoxescX94xeg8o5IOT6vNVJV1MK61EJmd1as6aKBhzmo4kxyHnDYQGPhbwpzwKMxhpcOjX3Mvr7YoLbRvnhddHU2TXrC9yRhaDF/Iu/Uu1uoSdfZ3XifIAywRH/TYqEqZbwW0T3bRZ8qqt3JrA2PGAYQ9+HDjm+7Thg4xW2QuOnvmWK9gumK2NQgdzINQR+iC+hFRszD5rMSy4867LlJYJgxrZcW801w4wzYIc0QhP0VktYl1OG35b8FXqVtMV2D23G8mVg6K2MGqv1A/JTEQU7MAz3C+P+XhQDvrynDeRh3XLsaNSJlj7RMx/OSLnSg4xPZ+PO7Uj/kqmdLb9XHjhNnE609CH3Kn5NgdR2sE+/sZYI9jkWbT3sxvuVdQBnrSdbzXAKLp0V/GHAP6ymw/ci7U+TGDMhiEU+U53O/oNAQ2BVhYL8IIvtygPUK+QT/L5OW12tbtSK/2Sa8Au6jf5OPHusoc6tormk= # DOCKER_USER
  - secure: ZEjIXow+plBGsZyjWqytSHHGCacAAD6Gdj+NmFK+JDdL4F9i2ndhDl8pcaunr6PHQWXgzyNWt9YOauQWGuiUSwIyJBkkSzC1KRCZXQR/ZxrJEk9vSFcYHHTPCJgDNViiqo0l1gNYcP/Po/EpE6Fljs4JLveFh/zmetRHKE0vAvc5tfeDjXXRoEQ4CYF1yycWF21mCHg493UVK67FR+3XAeNi7of9ZIT4iGmxUH+9Htd5srhkdDTTJqqwEe1Ql5EJ3LW5+Ssj8fRDNr7vgTnLz9wb8Wv9Ez3/q2Fukv1VIB4rWTMmUERxzWkxyu05tK2DYOFrSN8LQdJVu+pzRl0qHmQSITwekCq974Bav89BvkoEb7xT0kbCwZOLswqVBt+jLOBRLBUmlZn7REkRGcBEHNhIR82q4hVS7aZHeLIx8QGYoREKKKKVcvEr+LxucqvsO6RbGtkeqUjOmv4q8qzWrewGuzS5J+NmI9V7h3QWGyDVU/cdKf6lyo9nmnZ8YmUp5xeKwaiL1yfO7K16jxYnNQvfnPc+3VmiX8Wb8PRAxUysmY2fCQJIyMsSSSNaHv7dA0AJFRqOeZDzaPHN5zOHS8mvSBou4Sq878R97poFkU5k9PWFkQ0pc+fSh07L1wClMosqd2qpxEypFxWV5DkQKZk3gF+mnrsvrKoKcy1CB68= # DOCKER_PASS
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - openssl aes-256-cbc -K $encrypted_7deda1f68196_key -iv $encrypted_7deda1f68196_iv -in private/private.tar.enc -out private/private.tar -d
  - tar xvf private/private.tar
  - mv v7_9-01727L.zip vendor/.

script:
  - docker run -v $PWD:/sipi dhlabbasel/sipi-base /bin/sh -c "cd /sipi/build; cmake ..; make; make check"

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=dhlabbasel/sipi
  - export TAG=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "latest"; else echo ${TRAVIS_BRANCH//\//-} $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  slack:
    secure: MGtrlgeHZ8F6SHmMOyOVuUac4IVSW7MF5tYGOHrRxyYuUZ5H/mADF/nHrY1wWwn9YHB460TkIma48/ctC21wyFecfvSzxfBuJtFflsXSpe8gE9DnlWaSZJgrcC7KwNcxDi4+0wIQHvFg8jbUZflsI1sB0ctMLzlt8gKQqRzjnlttznxUnU+8iEkUrPqRpFrwdL84J38Pdi4xy+7cMlx6VfaBj2UcBQz+jN22fJqOq4haCAj1w/ExrZJ1FaXJlgGafYQLV2YBeIdXrKNVV1dXpGElpOybuFbsi0XWHxHBaEALgoTZHot9QX3NXeRlm5BLVtqYXo06jFVydnnkvup44HYgPH6IFSbe4lh4kS+NKn+zbKjHwcPN2RZEvICmdpU9Gz/c0RVCPOp1NUQnnrMPcU8Q3X9LSa//y+X1nawk3vzjqeecLNZ6hJ6BAzzhF7Sy8kP5irTpGozwJtSZl8dQZX67sG7AQRpKhNw1HwGQSToasmPy8yQyVGozCoXS1m0R381xczNJcm8Ah2ApFT77VkglMwGtktWGGnYlXImwnKBK+DwJvQVkCtQ8bI5ZcGOOkH41zZ0QJ851eUMMrn2L7DDpBiZFXfp9BTWuBSIJtXTQ1SYldundmOJLKswx2rl+swngdF4cWS37lGMTiebpuxalWQ0O4uhflm7tRb0Kx9I=
