# get us a vm with ubuntu 16.04
dist: trusty
sudo: required

# only pull the last commit (faster)
git:
  depth: 1

# provides us docker
services:
  - docker

language: cpp

# define some additional environment variables
env:
  global:
    - REPO=dhlabbasel/sipi

stages:
  - test
  - name: publish # generally, only publish if we are on 'develop' or tagged
    if: branch = develop OR tag IS present

jobs:
  include:
    - stage: test
      script:
        # decrypt archive containing the kakadu library
        - openssl aes-256-cbc -K $encrypted_b6ef6f57f289_key -iv $encrypted_b6ef6f57f289_iv -in vendor/v7_A_7-01382N.zip.enc -out vendor/v7_A_7-01382N.zip -d
        # run compile and tests inside docker
        - docker run -it --rm -v $PWD:/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "mkdir -p /sipi/build-linux && cd /sipi/build-linux && cmake .. && make && ctest --verbose"

    - stage: publish
      script:
        # decrypt archive containing the kakadu library
        - openssl aes-256-cbc -K $encrypted_b6ef6f57f289_key -iv $encrypted_b6ef6f57f289_iv -in vendor/v7_A_7-01382N.zip.enc -out vendor/v7_A_7-01382N.zip -d
        # login into docker hub, build image, and push but only when on the "develop" branch or tagged
        # when on 'develop' then $TRAVIS_BRANCH = develop
        # when on 'tag' then $TRAVIS_BRANCH = tag, e.g., v1.2.0
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker build -t $REPO:$TRAVIS_BRANCH .
        - docker tag $REPO:$TRAVIS_BRANCH $REPO:latest
        - docker push $REPO

notifications:
  slack:
    secure: "PxvA5zguh3T64J+c7JHnXtKM9jo8S5qIDJ6IT7d2l66xI48Hf3hiM/Tr9C+Duc1krrMViB935AzDFaK5QZPOgzbzHd1AMugLTSD/ds+puimZ8W8gwZVH3MkYyqPXVofCEZaCKPbGOQTQ5Z6wAaGLZ2wuaAwMaqvKi8fMPc6r7M/Ggaagsiw8t9ScRcMTFt2PbmXfdcazIaPigMramLFXDel+AgFW3ay5D9ophs2QsfRlNAxd1OxAHZFIgoimI13H9fM7Efs1TWBywqUVkd9Fsl5aiY5zEcJN7NezgAJrUynL9FJwPBV+NcOAfm/WBqJ82K0zCSE2blhLr2ixVsfhuceEUXVa/2Y1qthOkKFEgggcfnth7D12RjLOY5Qr8J8f9q45A1cTqsiitKS9qfgulcV1fNqho4X9EROrVY20Li9eWNDQOK4EiHclpfnBZ1NVH0DrRt7y19zdyW749RUOy9NO1MMhjl93E6K9KELVGlfCOsm9ZxKGzZsV4XA3nClXlIn7IdE7jlc/bmyC0nWf8HGge8l+HSJp0c4F078VOF5eIq3aNm9H740736ycSr/W6Puj34QblFTslR4/7qCDtfB/Hf7HNyPSK+thiHlNUZa4WeOT7lb/iDHevpCBQ2+HFQFfxwLIFbC+jlZKQfRNHIwoHG5rzCZPf1stUtREKN0="
