site_name: SIPI Documentation

nav:
  - Overview: index.md
  - Building: building.md
  - Running: running.md
  - Lua: lua.md
  - Developing: developing.md
  - Release-Notes: 0-release-notes/index.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep blue'
    accent: 'deep blue'
  feature:
    tabs: false
extra_css:
  - 'assets/style/theme.css'
