site_name: SIPI Documentation

repo_url: https://github.com/dasch-swiss/sipi
repo_name: dasch-swiss/sipi
edit_uri: blob/main/docs/
copyright: "&copy; 2017 - 2021 <a href='https://dasch.swiss' target='_blank'>Data and Service Center for the Humanities (DaSCH)</a>"

nav:
  - Introduction: introduction.md
  - Basic information and Reference: sipi.md
  - Lua integration: lua.md
  - Lua imaging functions: lua-image.md
  - Sqlite3 integration: sqlite.md
  - Building: building.md
  - Running: running.md
  - Developing: developing.md
  - Release-Notes: 0-release-notes/index.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep blue'
    accent: 'deep blue'
  feature:
    tabs: false
extra_css:
  - 'assets/style/theme.css'
