name: "Start Debug Session"
description: "Starts a debugging session of the self-hosted runner"
inputs: SSH_GATEWAY_IP

runs:
  using: "composite"
  steps:
    - name: Setup SSH server for Actor
      uses: alexellis/setup-sshd-actor@master
    - name: Connect to the actuated SSH gateway
      uses: alexellis/actuated-ssh-gateway-action@master
      with:
        gatewayaddr: ${{ secrets.SSH_GATEWAY_IP }}
        secure: true
    - name: Setup a blocking tmux session
      uses: alexellis/block-with-tmux-action@master
