name: "Checkout"
description: "Checkout code and ci-assets"
inputs:
  DASCHBOT_PAT:
    description: "daschbot's private access token"
    required: true
  GIT_CRYPT_KEY:
    description: "The key to decrypt files with git-crypt"
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: checkout private ci-assets
      uses: actions/checkout@v4
      with:
        repository: dasch-swiss/dsp-ci-assets
        token: ${{ inputs.DASCHBOT_PAT }} # `DASCHBOT_PAT` is a secret that contains your PAT
        path: ci
    - name: copy ci-assets
      shell: bash
      run: cp $GITHUB_WORKSPACE/ci/kakadu/v8_4_1-01382N.zip $GITHUB_WORKSPACE/vendor/v8_4_1-01382N.zip
