/*
 * Copyright © 2026 Swiss National Data and Service Center for the Humanities
 * and/or DaSCH Service Platform contributors. SPDX-License-Identifier:
 * AGPL-3.0-or-later
 */

// Decode-path memory-safety regression suite for crafted malformed TIFF
// fixtures (DEV-6064, DEV-6065, DEV-6067, N3, N6). Fixtures live under
// test/_test_data/images/malformed/ (generated by
// //test/unit/fixtures:generate_malformed_images); see that directory's
// README.md for what each file's defect is. This is the DECODE path only
// (SipiImage::read()) — a JPX write path is out of scope here (unrelated
// Kakadu PALETTE_Conversion SIGILL on some platforms).

#include "gtest/gtest.h"

#include "error/SipiValueError.h"
#include "image/SipiImage.h"
#include "test_paths.h"

namespace {

std::string malformed_path(const char *name)
{
  return sipi::test::data_dir() + "/images/malformed/" + name;
}

}// namespace

// DEV-6063: a TIFF header claiming a width far beyond SipiIO's
// kMaxDecodeDim must be rejected before any pixel buffer is sized or
// allocated. libtiff itself refuses to open the malformed directory
// (TIFFOpen returns null), so the handler reports "not mine" and every
// other registered handler agrees, which read() surfaces as the terminal
// "no registered format handler recognised it" error.
TEST(MalformedTiff, OversizedDimensionsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_oversized_dimensions.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N6: a palette TIFF whose BitsPerSample (32) falls outside the supported
// set must be rejected before the colormap length (1 << bps) is computed.
// Same "TIFFOpen refuses the directory" mechanism as OversizedDimensionsThrows.
TEST(MalformedTiff, ColormapUnsupportedBpsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_colormap_unsupported_bps.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N3: a grayscale TIFF with WhitePoint + TransferFunction (no embedded ICC
// profile) must decode successfully via the corrected variadic
// TIFFGetField(TIFFTAG_TRANSFERFUNCTION, ...) call — one uint16_t*
// out-pointer for a grayscale (SamplesPerPixel - ExtraSamples == 1) image.
TEST(MalformedTiff, TransferFunctionGrayscaleDecodesCleanly)
{
  Sipi::SipiImage img;
  ASSERT_TRUE(img.read(malformed_path("tiff_transferfunction_grayscale.tif")).has_value());
  EXPECT_EQ(img.getNx(), 8U);
  EXPECT_EQ(img.getNy(), 8U);
}

// DEV-6064 / DEV-6065: a 1-bit-per-sample palette TIFF with a 2-entry
// colormap. Before DEV-6064's fix, `rcm`/`gcm`/`bcm` were only reserve()'d
// (size 0, capacity 2) and indexed via operator[] regardless — undefined
// behavior for every index, in-range or not. SipiIOTiff's sub-8-bit palette
// unpacking also does not special-case PALETTE the way the 4-bit/12-bit
// unpackers do, so a decoded pixel value is not structurally guaranteed to
// stay within the colormap's bounds; the validate-before-lookup guard added
// at the palette-to-RGB expansion step (DEV-6065) must fail closed
// (an error Result) rather than read past rcm/gcm/bcm if it ever doesn't.
// Either outcome (clean decode or a rejected Result) is acceptable here —
// the regression this guards against is a crash / OOB read.
TEST(MalformedTiff, PaletteOneBitDoesNotCrash)
{
  Sipi::SipiImage img;
  // Rejecting an out-of-range palette index (delivered as an error Result) is
  // an acceptable outcome, equally with a clean decode; reaching this point
  // without SIGSEGV/SIGABRT is the assertion.
  [[maybe_unused]] auto r = img.read(malformed_path("tiff_palette_1bit.tif"));
}

// A well-formed grayscale TIFF carrying a TIFFTAG_ICCPROFILE payload that is
// not a valid ICC profile: a 128-byte buffer (the fixed ICC header size)
// whose declared size matches the buffer but has no `acsp` signature at
// offset 36. SipiIOTiff::read() reads TIFFTAG_ICCPROFILE with no length or
// bounds check of its own and passes the bytes straight to Icc::parse(),
// so this is lcms2's cmsOpenProfileFromMem() itself rejecting the profile,
// not an upstream bounds guard. Regresses SipiIOTiff::read()'s
// fatal-metadata contract (DEV-7056): a file whose embedded ICC profile
// fails to parse is refused with kMetadataParseFailed, surfaced from
// read() (SipiImage::read() calls SipiIOTiff::read() directly; there is no
// separate read_shape() rejection path for this defect).
TEST(MalformedTiff, IccGarbageFailsMetadataParse)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_icc_garbage.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kMetadataParseFailed);
}
