name: "Setup python and install libraries"
description: "Setup python and install libraries"

runs:
  using: "composite"
  steps:
    - name: Install Python
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt install -qyyy --no-install-recommends python3.11 python3-pip python3.11-distutils 
        sudo ln -nsf /usr/bin/python3.11 /usr/bin/python3
        sudo python3 -m ensurepip --upgrade
