name: "Setup python and install libraries"
description: "Setup python and install libraries"

inputs:
  version:
    description: "Python version to install"
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Install Python
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt install -qyyy --no-install-recommends python${{inputs.version}} python${{inputs.version}}-dev python${{inputs.version}}-distutils 
        sudo ln -nsf /usr/bin/python${{inputs.version}} /usr/bin/python3
    - name: Install PIP
      shell: bash
      run: |
        which pip || curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
    - name: Upgrade pip and setuptools
      shell: bash
      run: |
        pip3 install --upgrade pip setuptools wheel
