/*
 * Copyright © 2016 - 2026 Swiss National Data and Service Center for the Humanities and/or DaSCH Service Platform
 * contributors. SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Regression tests for JPEG marker-parsing over-reads (DEV-6066, N1, N4):
 *
 *  - `SipiIOJpeg::read_shape()`'s XMP marker walk tracked how far it had
 *    scanned with a counter that started at 0 from the position `memmem()`
 *    found the XMP namespace header, not from the start of `marker->data`.
 *    It could therefore walk up to `marker->data_length` bytes past the end
 *    of the marker's heap-allocated buffer looking for an `<?xpacket>`
 *    wrapper that does not exist (DEV-6066).
 *  - `SipiIOJpeg::read()`'s ICC (APP2) length computation
 *    (`data_length - offset - 14`) could underflow when the `ICC_PROFILE`
 *    identifier was found too close to the end of the segment, turning a
 *    short marker into a huge copy length (N1).
 *  - Both `read()` and `read_shape()` compared the first 14 bytes of an
 *    APP13 segment against `"Photoshop 3.0\0"` via `strncmp` without first
 *    checking `marker->data_length`, over-reading a short segment (N4).
 *  - `parse_photoshop()`'s 8BIM resource walk added the Pascal name-length
 *    byte and then an odd->even padding byte to `slen` before advancing
 *    `ptr`, without re-checking the padded length against the remaining
 *    bytes. A resource whose even-length name ends exactly at the marker's
 *    data end pushed `ptr` one byte past `end`; the next `4 > (size_t)(end -
 *    ptr)` then evaluated `end - ptr == -1`, cast to `SIZE_MAX`, defeated the
 *    guard and over-read `datalen` and beyond (the adversarial review's most
 *    severe finding). Guarded by `if (slen > (size_t)(end - ptr)) break;`
 *    (and the sibling `datalen` guard) before each advance.
 *
 * Also covers DEV-7056: `read()`'s EXIF extraction hands the APP1 payload
 * past the `Exif\0\0` identifier to `Exif::parse()` once every bounds guard
 * above has cleared it. A payload that reaches `Exif::parse()` and is not
 * itself valid TIFF makes `Exiv2::ExifParser::decode()` throw, which
 * `read()` reports as `ErrorCode::kMetadataParseFailed` — SIPI, as a
 * repository, must not admit a file whose embedded metadata does not parse.
 *
 * Also covers DEV-7078: an embedded ICC profile with a well-formed header
 * but a zero tag count has no description tag. `cmsGetProfileInfoASCII`
 * then reports length 0, and `Icc::parse()` must classify the profile as
 * `icc_unknown` instead of reading past the resulting zero-length buffer.
 *
 * Fixtures are generated by
 * test/unit/fixtures/generate_jpeg_fixtures.py
 * (`generate_malformed()`); see
 * test/_test_data/images/malformed/README.md for each fixture's exact
 * defect. A non-sanitized local run cannot itself detect an over-read (see
 * CI's ASan legs for that) — the fixture plus a "no crash, clean result"
 * assertion is the regression pin.
 */

#include "gtest/gtest.h"

#include "error/SipiValueError.h"
#include "image/SipiImage.h"
#include "image/SipiImageError.h"
#include "SipiIOJpeg.h"
#include "test_paths.h"

#include <string>

namespace {

// `sipi::test::data_dir()` honours Bazel's SIPI_TEST_DATA_DIR env and falls
// back to the historical CMake build-tree relative path when unset. See
// test/test_paths.h.
static const std::string kMalformedRoot = sipi::test::data_dir() + "/images/malformed";
static const std::string kXmpTruncated = kMalformedRoot + "/jpeg_xmp_truncated.jpg";
static const std::string kIccShortApp2 = kMalformedRoot + "/jpeg_icc_short_app2.jpg";
static const std::string kIccNoDescription = kMalformedRoot + "/jpeg_icc_no_description.jpg";
static const std::string kPhotoshopShortApp13 = kMalformedRoot + "/jpeg_photoshop_short_app13.jpg";
static const std::string kPhotoshopOvershootApp13 = kMalformedRoot + "/jpeg_photoshop_overshoot_app13.jpg";
static const std::string kExifTruncated = kMalformedRoot + "/jpeg_exif_truncated.jpg";

}// namespace

// -------------------------------------------------------------------------
// DEV-6066 — read_shape() XMP marker walk
// -------------------------------------------------------------------------

TEST(JpegMarkerRegression, XmpTruncatedReadShapeDoesNotCrash)
{
  Sipi::SipiIOJpeg io;
  Sipi::Result<Sipi::SipiImgInfo> result{ Sipi::SipiImgInfo{} };
  // The bounded extraction must not walk past marker->data_length; the
  // underlying JPEG image data is well-formed, so the shape probe still
  // succeeds once the XMP segment is safely skipped.
  ASSERT_NO_THROW(result = io.read_shape(kXmpTruncated));
  ASSERT_TRUE(result.has_value());
  const auto &info = *result;
  EXPECT_EQ(info.success, Sipi::SipiImgInfo::DIMS);
  EXPECT_GT(info.width, 0);
  EXPECT_GT(info.height, 0);
}

TEST(JpegMarkerRegression, XmpTruncatedFullReadDoesNotCrash)
{
  Sipi::SipiImage img;
  EXPECT_TRUE(img.read(kXmpTruncated).has_value());
}

// -------------------------------------------------------------------------
// N1 — read() ICC (APP2) length underflow
// -------------------------------------------------------------------------
//
// read_shape() does not process APP2/ICC markers at all (only JPEG_COM,
// APP1 EXIF/XMP, and APP13 Photoshop) — the ICC underflow guard only
// applies to the full read() path, so this fixture is exercised there.

TEST(JpegMarkerRegression, IccShortApp2ReadDoesNotCrash)
{
  Sipi::SipiImage img;
  EXPECT_TRUE(img.read(kIccShortApp2).has_value());
}

// -------------------------------------------------------------------------
// DEV-7078 — Icc::parse() classification of a description-less profile
// -------------------------------------------------------------------------
//
// Unlike jpeg_icc_short_app2.jpg (which pins the N1 bounds guard and never
// reaches Icc::parse()), this fixture carries a well-formed APP2 ICC
// segment whose profile has a valid header but zero tags — no description
// tag — so the embedded bytes do reach Icc::parse(), and the read must both
// succeed and classify the profile as icc_unknown.

TEST(JpegMarkerRegression, IccNoDescriptionClassifiesAsUnknown)
{
  Sipi::SipiImage img;
  auto result = img.read(kIccNoDescription);
  ASSERT_TRUE(result.has_value());
  const auto icc = img.getIcc();
  ASSERT_NE(icc, nullptr);
  EXPECT_EQ(icc->getProfileType(), Sipi::icc_unknown);
}

// -------------------------------------------------------------------------
// N4 — APP13 Photoshop identifier guard (read() and read_shape())
// -------------------------------------------------------------------------

TEST(JpegMarkerRegression, PhotoshopShortApp13ReadShapeDoesNotCrash)
{
  Sipi::SipiIOJpeg io;
  Sipi::Result<Sipi::SipiImgInfo> result{ Sipi::SipiImgInfo{} };
  ASSERT_NO_THROW(result = io.read_shape(kPhotoshopShortApp13));
  ASSERT_TRUE(result.has_value());
  const auto &info = *result;
  EXPECT_EQ(info.success, Sipi::SipiImgInfo::DIMS);
}

TEST(JpegMarkerRegression, PhotoshopShortApp13FullReadDoesNotCrash)
{
  Sipi::SipiImage img;
  EXPECT_TRUE(img.read(kPhotoshopShortApp13).has_value());
}

// -------------------------------------------------------------------------
// parse_photoshop() even-padding pointer overshoot (adversarial review)
// -------------------------------------------------------------------------
//
// A *valid* "Photoshop 3.0\0" identifier (so the caller's data_length + strncmp
// guard passes and parse_photoshop() actually runs) followed by exactly one
// 7-byte 8BIM resource with an empty (even-length) Pascal name and nothing
// after it. The name-length byte plus the odd->even padding bump pushed `ptr`
// one byte past `end`; the next bounds check then computed `end - ptr == -1`,
// cast to SIZE_MAX, and over-read past the marker's heap buffer. Under ASan
// (CI) the pre-fix over-read aborts here; locally the fixture still decodes
// because the crafted resource is skipped once the padded-length guard breaks.

TEST(JpegMarkerRegression, PhotoshopOvershootApp13ReadShapeDoesNotCrash)
{
  Sipi::SipiIOJpeg io;
  Sipi::Result<Sipi::SipiImgInfo> result{ Sipi::SipiImgInfo{} };
  ASSERT_NO_THROW(result = io.read_shape(kPhotoshopOvershootApp13));
  ASSERT_TRUE(result.has_value());
  const auto &info = *result;
  EXPECT_EQ(info.success, Sipi::SipiImgInfo::DIMS);
  EXPECT_GT(info.width, 0);
  EXPECT_GT(info.height, 0);
}

TEST(JpegMarkerRegression, PhotoshopOvershootApp13FullReadDoesNotCrash)
{
  Sipi::SipiImage img;
  EXPECT_TRUE(img.read(kPhotoshopOvershootApp13).has_value());
}

// -------------------------------------------------------------------------
// DEV-7056 — Exif::parse() failure is fatal (not a bounds guard)
// -------------------------------------------------------------------------
//
// The APP1 payload is `Exif\0\0` followed by a truncated little-endian TIFF
// header ("II*", 3 bytes: no magic-number low byte, no IFD offset, no IFD).
// It is long enough to clear every length check upstream of the parser, so
// `read()` actually calls `Exif::parse()`, which calls
// `Exiv2::ExifParser::decode()`; that throws on the malformed TIFF structure
// and `read()` reports the failure as `kMetadataParseFailed` rather than
// admitting the file with corrupt embedded metadata.

TEST(JpegMarkerRegression, ExifTruncatedFullReadFailsWithMetadataParseFailed)
{
  Sipi::SipiImage img;
  auto result = img.read(kExifTruncated);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), Sipi::ErrorCode::kMetadataParseFailed);
}
