/*
 * Copyright © 2026 Swiss National Data and Service Center for the Humanities
 * and/or DaSCH Service Platform contributors. SPDX-License-Identifier:
 * AGPL-3.0-or-later
 */

// Decode-path memory-safety regression suite for crafted malformed TIFF
// fixtures (DEV-6064, DEV-6065, DEV-6067, N3, N6). Fixtures live under
// test/_test_data/images/malformed/ (generated by
// //test/unit/fixtures:generate_malformed_images); see that directory's
// README.md for what each file's defect is. This is the DECODE path only
// (SipiImage::read()) — a JPX write path is out of scope here (unrelated
// Kakadu PALETTE_Conversion SIGILL on some platforms). The S2-02/S2-03 tests
// below are the exception: they exercise SipiIOJ2k's non-PALETTE JP2
// encode/decode paths, which do not trip that SIGILL.

#include "gtest/gtest.h"

#include "error/SipiValueError.h"
#include "iiifparser/SipiRegion.h"
#include "image/SipiImage.h"
#include "test_paths.h"

#include <cstdio>
#include <memory>

namespace {

std::string malformed_path(const char *name)
{
  return sipi::test::data_dir() + "/images/malformed/" + name;
}

}// namespace

// DEV-6063: a TIFF header claiming a width far beyond SipiIO's
// kMaxDecodeDim must be rejected before any pixel buffer is sized or
// allocated. libtiff itself refuses to open the malformed directory
// (TIFFOpen returns null), so the handler reports "not mine" and every
// other registered handler agrees, which read() surfaces as the terminal
// "no registered format handler recognised it" error.
TEST(MalformedTiff, OversizedDimensionsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_oversized_dimensions.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N6: a palette TIFF whose BitsPerSample (32) falls outside the supported
// set must be rejected before the colormap length (1 << bps) is computed.
// Same "TIFFOpen refuses the directory" mechanism as OversizedDimensionsThrows.
TEST(MalformedTiff, ColormapUnsupportedBpsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_colormap_unsupported_bps.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N3: a grayscale TIFF with WhitePoint + TransferFunction (no embedded ICC
// profile) must decode successfully via the corrected variadic
// TIFFGetField(TIFFTAG_TRANSFERFUNCTION, ...) call — one uint16_t*
// out-pointer for a grayscale (SamplesPerPixel - ExtraSamples == 1) image.
TEST(MalformedTiff, TransferFunctionGrayscaleDecodesCleanly)
{
  Sipi::SipiImage img;
  ASSERT_TRUE(img.read(malformed_path("tiff_transferfunction_grayscale.tif")).has_value());
  EXPECT_EQ(img.getNx(), 8U);
  EXPECT_EQ(img.getNy(), 8U);
}

// DEV-6064 / DEV-6065: a 1-bit-per-sample palette TIFF with a 2-entry
// colormap. Before DEV-6064's fix, `rcm`/`gcm`/`bcm` were only reserve()'d
// (size 0, capacity 2) and indexed via operator[] regardless — undefined
// behavior for every index, in-range or not. SipiIOTiff's sub-8-bit palette
// unpacking also does not special-case PALETTE the way the 4-bit/12-bit
// unpackers do, so a decoded pixel value is not structurally guaranteed to
// stay within the colormap's bounds; the validate-before-lookup guard added
// at the palette-to-RGB expansion step (DEV-6065) must fail closed
// (an error Result) rather than read past rcm/gcm/bcm if it ever doesn't.
// Either outcome (clean decode or a rejected Result) is acceptable here —
// the regression this guards against is a crash / OOB read.
TEST(MalformedTiff, PaletteOneBitDoesNotCrash)
{
  Sipi::SipiImage img;
  // Rejecting an out-of-range palette index (delivered as an error Result) is
  // an acceptable outcome, equally with a clean decode; reaching this point
  // without SIGSEGV/SIGABRT is the assertion.
  [[maybe_unused]] auto r = img.read(malformed_path("tiff_palette_1bit.tif"));
}

// A well-formed grayscale TIFF carrying a TIFFTAG_ICCPROFILE payload that is
// not a valid ICC profile: a 128-byte buffer (the fixed ICC header size)
// whose declared size matches the buffer but has no `acsp` signature at
// offset 36. SipiIOTiff::read() reads TIFFTAG_ICCPROFILE with no length or
// bounds check of its own and passes the bytes straight to Icc::parse(),
// so this is lcms2's cmsOpenProfileFromMem() itself rejecting the profile,
// not an upstream bounds guard. Regresses SipiIOTiff::read()'s
// fatal-metadata contract (DEV-7056): a file whose embedded ICC profile
// fails to parse is refused with kMetadataParseFailed, surfaced from
// read() (SipiImage::read() calls SipiIOTiff::read() directly; there is no
// separate read_shape() rejection path for this defect).
TEST(MalformedTiff, IccGarbageFailsMetadataParse)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_icc_garbage.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kMetadataParseFailed);
}

// S2-01: a PLANARCONFIG_SEPARATE, LZW-compressed RGB TIFF cropped to a
// region with roi_y > 0 must not corrupt memory. Before the fix,
// read_standard_data()'s PLANARCONFIG_SEPARATE branches (both the
// uncompressed and the compressed variant) wrote each channel's rows at
// `nc * roi_w + roi_h + i * roi_w`, an absolute-row (not ROI-relative)
// destination offset that overflows `inbuf` for any roi_y > 0 — an
// out-of-bounds write only observed under the CI asan-ubsan leg (local
// ASan is broken on this toolchain). This test asserts the post-fix
// decode is not just crash-free but pixel-correct: `tiff_planar_separate_lzw_rgb.tif`
// is a 16x16 fixture with a deterministic per-channel gradient
// (R = x*16 mod 256, G = y*16 mod 256, B = (x+y)*8 mod 256), and the
// region requested here is the bottom-right 8x8 quadrant (roi_x=8,
// roi_y=8), so roi_y > 0 exercises the previously-broken offset.
TEST(MalformedTiff, PlanarSeparateRoiNearBottomEdgeDecodesCorrectly)
{
  Sipi::SipiImage img;
  auto region = std::make_shared<Sipi::SipiRegion>(8, 8, 8, 8);
  const auto r = img.read(malformed_path("tiff_planar_separate_lzw_rgb.tif"), region);
  ASSERT_TRUE(r.has_value());
  EXPECT_EQ(img.getNx(), 8U);
  EXPECT_EQ(img.getNy(), 8U);
  EXPECT_EQ(img.getNc(), 3U);
  // local (0,0) -> global (8,8): R=128, G=128, B=128
  EXPECT_EQ(img.getPixel(0, 0, 0), 128);
  EXPECT_EQ(img.getPixel(0, 0, 1), 128);
  EXPECT_EQ(img.getPixel(0, 0, 2), 128);
  // local (7,7) -> global (15,15): R=240, G=240, B=240
  EXPECT_EQ(img.getPixel(7, 7, 0), 240);
  EXPECT_EQ(img.getPixel(7, 7, 1), 240);
  EXPECT_EQ(img.getPixel(7, 7, 2), 240);
  // local (3,5) -> global (11,13): R=176, G=208, B=192
  EXPECT_EQ(img.getPixel(3, 5, 0), 176);
  EXPECT_EQ(img.getPixel(3, 5, 1), 208);
  EXPECT_EQ(img.getPixel(3, 5, 2), 192);
}

// S2-06: a TILED, PLANARCONFIG_SEPARATE RGBA TIFF must not read `nc` planes
// out of a one-plane tile buffer. Before the fix, `read_tiled_data()` read a
// single (sample-0) plane per tile via `TIFFReadTile(..., /*sample=*/0)` into
// a `tile_size`-sized buffer, then handed that one-plane buffer to
// `separateToContig()` as if it held `nc` interleaved planes — reading
// `(nc - 1) * tile_size` bytes of adjacent heap into the decoded image. This
// is a heap-buffer-overflow read (heap disclosure), observable as an ASan
// over-read on the CI asan-ubsan leg (local ASan is broken on this
// toolchain). `tiff_tiled_planar_separate_rgba.tif` is a 32x32, 16x16-tiled,
// 4-sample (RGBA) fixture spanning a 2x2 tile grid with a deterministic
// per-channel gradient (R = x*7 mod 256, G = y*5 mod 256,
// B = (x+y)*3 mod 256, A = 255 - (x*y mod 256)); this test asserts the
// post-fix decode is pixel-correct at the origin, at a tile-interior pixel,
// at a pixel immediately across a tile boundary, and at the far corner —
// proving no adjacent-heap bytes leak into any of the four tiles.
TEST(MalformedTiff, TiledPlanarSeparateRgbaDecodesCorrectly)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_tiled_planar_separate_rgba.tif"));
  ASSERT_TRUE(r.has_value());
  EXPECT_EQ(img.getNx(), 32U);
  EXPECT_EQ(img.getNy(), 32U);
  EXPECT_EQ(img.getNc(), 4U);
  // (0, 0): R=0, G=0, B=0, A=255
  EXPECT_EQ(img.getPixel(0, 0, 0), 0);
  EXPECT_EQ(img.getPixel(0, 0, 1), 0);
  EXPECT_EQ(img.getPixel(0, 0, 2), 0);
  EXPECT_EQ(img.getPixel(0, 0, 3), 255);
  // (15, 15): last pixel of the top-left tile. R=105, G=75, B=90, A=30
  EXPECT_EQ(img.getPixel(15, 15, 0), 105);
  EXPECT_EQ(img.getPixel(15, 15, 1), 75);
  EXPECT_EQ(img.getPixel(15, 15, 2), 90);
  EXPECT_EQ(img.getPixel(15, 15, 3), 30);
  // (16, 16): first pixel of the bottom-right tile. R=112, G=80, B=96, A=255
  EXPECT_EQ(img.getPixel(16, 16, 0), 112);
  EXPECT_EQ(img.getPixel(16, 16, 1), 80);
  EXPECT_EQ(img.getPixel(16, 16, 2), 96);
  EXPECT_EQ(img.getPixel(16, 16, 3), 255);
  // (31, 31): far corner. R=217, G=155, B=186, A=62
  EXPECT_EQ(img.getPixel(31, 31, 0), 217);
  EXPECT_EQ(img.getPixel(31, 31, 1), 155);
  EXPECT_EQ(img.getPixel(31, 31, 2), 186);
  EXPECT_EQ(img.getPixel(31, 31, 3), 62);
}

// S2-08: a TIFF whose corrupted IFD makes libtiff's own `TIFFScanlineSize()`
// smaller than SIPI's independently-computed per-scanline byte count
// (`nx * SamplesPerPixel * BitsPerSample / 8`) must be rejected before
// `read_standard_data()` copies a SIPI-sized chunk into the
// `TIFFScanlineSize()`-allocated scanline buffer. `tiff_scanline_undersized.tif`
// is the verbatim nightly libFuzzer/ASan crash reproducer for this defect
// (a heap-buffer-overflow read in the contiguous-scanline memcpy); this test
// asserts a clean rejection rather than the crash.
TEST(MalformedTiff, ScanlineUndersizedRejectsCleanly)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_scanline_undersized.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kMalformedInput);
}

// S2-02: an 8-component image (5 more than the fixed-size `int
// stripe_heights[5]` array SipiIOJ2k::write() used to declare) must encode
// to JP2 without corrupting the stack. `tiff_eight_sample.tif` is a 16x16,
// 8-bit, 8-sample (RGB + 5 unspecified extra samples) TIFF; regresses the
// `push_stripe` stripe-heights buffer being sized from `img->getNc()`
// (a `std::vector<int>`) instead of the fixed 5-element array (S2-02).
TEST(MalformedTiff, EightSampleTiffEncodesToJp2Cleanly)
{
  Sipi::SipiImage img;
  ASSERT_TRUE(img.read(malformed_path("tiff_eight_sample.tif")).has_value());
  ASSERT_EQ(img.getNc(), 8U);

  const std::string dst = sipi::test::tmp_dir() + "/_j2k_eight_sample_write_test.jp2";
  ASSERT_TRUE(img.write("jpx", dst).has_value());
  std::remove(dst.c_str());
}

// S2-03: an 8-component JP2 (same overrun as S2-02, but on the decode side's
// `pull_stripe` call) must decode cleanly. `j2k_eight_component.jp2` is the
// JP2 encoding of `tiff_eight_sample.tif`; regresses the stripe-heights
// buffer being sized from `codestream.get_num_components()` instead of the
// fixed 5-element array (S2-03).
TEST(MalformedTiff, EightComponentJp2DecodesCleanly)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("j2k_eight_component.jp2"));
  ASSERT_TRUE(r.has_value());
  EXPECT_EQ(img.getNx(), 16U);
  EXPECT_EQ(img.getNy(), 16U);
  EXPECT_EQ(img.getNc(), 8U);
}

// Nightly `tiff_roundtrip` ASan finding (2026-09-07/08): a container-overflow
// WRITE in `Exiv2::append` on the memcpy that follows `blob.resize()`, reached
// from `SipiIOJ2k::write()` → `Exif::exifBytes()`. The exiv2 code is
// standards-correct and the same input converts cleanly outside the fuzz
// binary, so this test pins the exact decode-then-JP2-write path on the
// verbatim reproducer. It passes under the CI ASan job, which does not link
// libFuzzer, so the fuzz report is an artifact of that link (see the ASan
// step of `.github/workflows/fuzz.yml`), not a defect.
TEST(MalformedTiff, ExifMakeTiffEncodesToJp2Cleanly)
{
  Sipi::SipiImage img;
  ASSERT_TRUE(img.read(malformed_path("tiff_exif_make_jp2_roundtrip.tif")).has_value());
  ASSERT_NE(img.getExif(), nullptr);

  const std::string dst = sipi::test::tmp_dir() + "/_j2k_exif_make_roundtrip_test.jp2";
  ASSERT_TRUE(img.write("jpx", dst).has_value());
  std::remove(dst.c_str());
}
