/*
 * Copyright © 2026 Swiss National Data and Service Center for the Humanities
 * and/or DaSCH Service Platform contributors. SPDX-License-Identifier:
 * AGPL-3.0-or-later
 */

// Decode-path memory-safety regression suite for crafted malformed TIFF
// fixtures (DEV-6064, DEV-6065, DEV-6067, N3, N6). Fixtures live under
// test/_test_data/images/malformed/ (generated by
// //test/unit/fixtures:generate_malformed_images); see that directory's
// README.md for what each file's defect is. This is the DECODE path only
// (SipiImage::read()) — a JPX write path is out of scope here (unrelated
// Kakadu PALETTE_Conversion SIGILL on some platforms).

#include "gtest/gtest.h"

#include "error/SipiValueError.h"
#include "iiifparser/SipiRegion.h"
#include "image/SipiImage.h"
#include "test_paths.h"

#include <memory>

namespace {

std::string malformed_path(const char *name)
{
  return sipi::test::data_dir() + "/images/malformed/" + name;
}

}// namespace

// DEV-6063: a TIFF header claiming a width far beyond SipiIO's
// kMaxDecodeDim must be rejected before any pixel buffer is sized or
// allocated. libtiff itself refuses to open the malformed directory
// (TIFFOpen returns null), so the handler reports "not mine" and every
// other registered handler agrees, which read() surfaces as the terminal
// "no registered format handler recognised it" error.
TEST(MalformedTiff, OversizedDimensionsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_oversized_dimensions.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N6: a palette TIFF whose BitsPerSample (32) falls outside the supported
// set must be rejected before the colormap length (1 << bps) is computed.
// Same "TIFFOpen refuses the directory" mechanism as OversizedDimensionsThrows.
TEST(MalformedTiff, ColormapUnsupportedBpsThrows)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_colormap_unsupported_bps.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kUnsupportedFormat);
}

// N3: a grayscale TIFF with WhitePoint + TransferFunction (no embedded ICC
// profile) must decode successfully via the corrected variadic
// TIFFGetField(TIFFTAG_TRANSFERFUNCTION, ...) call — one uint16_t*
// out-pointer for a grayscale (SamplesPerPixel - ExtraSamples == 1) image.
TEST(MalformedTiff, TransferFunctionGrayscaleDecodesCleanly)
{
  Sipi::SipiImage img;
  ASSERT_TRUE(img.read(malformed_path("tiff_transferfunction_grayscale.tif")).has_value());
  EXPECT_EQ(img.getNx(), 8U);
  EXPECT_EQ(img.getNy(), 8U);
}

// DEV-6064 / DEV-6065: a 1-bit-per-sample palette TIFF with a 2-entry
// colormap. Before DEV-6064's fix, `rcm`/`gcm`/`bcm` were only reserve()'d
// (size 0, capacity 2) and indexed via operator[] regardless — undefined
// behavior for every index, in-range or not. SipiIOTiff's sub-8-bit palette
// unpacking also does not special-case PALETTE the way the 4-bit/12-bit
// unpackers do, so a decoded pixel value is not structurally guaranteed to
// stay within the colormap's bounds; the validate-before-lookup guard added
// at the palette-to-RGB expansion step (DEV-6065) must fail closed
// (an error Result) rather than read past rcm/gcm/bcm if it ever doesn't.
// Either outcome (clean decode or a rejected Result) is acceptable here —
// the regression this guards against is a crash / OOB read.
TEST(MalformedTiff, PaletteOneBitDoesNotCrash)
{
  Sipi::SipiImage img;
  // Rejecting an out-of-range palette index (delivered as an error Result) is
  // an acceptable outcome, equally with a clean decode; reaching this point
  // without SIGSEGV/SIGABRT is the assertion.
  [[maybe_unused]] auto r = img.read(malformed_path("tiff_palette_1bit.tif"));
}

// A well-formed grayscale TIFF carrying a TIFFTAG_ICCPROFILE payload that is
// not a valid ICC profile: a 128-byte buffer (the fixed ICC header size)
// whose declared size matches the buffer but has no `acsp` signature at
// offset 36. SipiIOTiff::read() reads TIFFTAG_ICCPROFILE with no length or
// bounds check of its own and passes the bytes straight to Icc::parse(),
// so this is lcms2's cmsOpenProfileFromMem() itself rejecting the profile,
// not an upstream bounds guard. Regresses SipiIOTiff::read()'s
// fatal-metadata contract (DEV-7056): a file whose embedded ICC profile
// fails to parse is refused with kMetadataParseFailed, surfaced from
// read() (SipiImage::read() calls SipiIOTiff::read() directly; there is no
// separate read_shape() rejection path for this defect).
TEST(MalformedTiff, IccGarbageFailsMetadataParse)
{
  Sipi::SipiImage img;
  const auto r = img.read(malformed_path("tiff_icc_garbage.tif"));
  ASSERT_FALSE(r.has_value());
  EXPECT_EQ(r.error().code(), Sipi::ErrorCode::kMetadataParseFailed);
}

// S2-01: a PLANARCONFIG_SEPARATE, LZW-compressed RGB TIFF cropped to a
// region with roi_y > 0 must not corrupt memory. Before the fix,
// read_standard_data()'s PLANARCONFIG_SEPARATE branches (both the
// uncompressed and the compressed variant) wrote each channel's rows at
// `nc * roi_w + roi_h + i * roi_w`, an absolute-row (not ROI-relative)
// destination offset that overflows `inbuf` for any roi_y > 0 — an
// out-of-bounds write only observed under the CI asan-ubsan leg (local
// ASan is broken on this toolchain). This test asserts the post-fix
// decode is not just crash-free but pixel-correct: `tiff_planar_separate_lzw_rgb.tif`
// is a 16x16 fixture with a deterministic per-channel gradient
// (R = x*16 mod 256, G = y*16 mod 256, B = (x+y)*8 mod 256), and the
// region requested here is the bottom-right 8x8 quadrant (roi_x=8,
// roi_y=8), so roi_y > 0 exercises the previously-broken offset.
TEST(MalformedTiff, PlanarSeparateRoiNearBottomEdgeDecodesCorrectly)
{
  Sipi::SipiImage img;
  auto region = std::make_shared<Sipi::SipiRegion>(8, 8, 8, 8);
  const auto r = img.read(malformed_path("tiff_planar_separate_lzw_rgb.tif"), region);
  ASSERT_TRUE(r.has_value());
  EXPECT_EQ(img.getNx(), 8U);
  EXPECT_EQ(img.getNy(), 8U);
  EXPECT_EQ(img.getNc(), 3U);
  // local (0,0) -> global (8,8): R=128, G=128, B=128
  EXPECT_EQ(img.getPixel(0, 0, 0), 128);
  EXPECT_EQ(img.getPixel(0, 0, 1), 128);
  EXPECT_EQ(img.getPixel(0, 0, 2), 128);
  // local (7,7) -> global (15,15): R=240, G=240, B=240
  EXPECT_EQ(img.getPixel(7, 7, 0), 240);
  EXPECT_EQ(img.getPixel(7, 7, 1), 240);
  EXPECT_EQ(img.getPixel(7, 7, 2), 240);
  // local (3,5) -> global (11,13): R=176, G=208, B=192
  EXPECT_EQ(img.getPixel(3, 5, 0), 176);
  EXPECT_EQ(img.getPixel(3, 5, 1), 208);
  EXPECT_EQ(img.getPixel(3, 5, 2), 192);
}
