name: release-please

on:
  push:
    branches:
      - main
  create:
    # This triggers for any tag or branch creation. We'll filter for tags in the job.

jobs:
  # Do the release-please thing
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'create' && startsWith(github.ref, 'refs/tags'))
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.DASCHBOT_PAT }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
