name: release-please

on:
  push:
    branches:
      - main

jobs:
  # Do the release-please thing
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.DASCHBOT_PAT }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
